version: "3.8"

services:
  wordpress:
    image: wordpress:php8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: raj_ecom_db
      WORDPRESS_DB_USER: raj_ecom_user
      WORDPRESS_DB_PASSWORD: raj_ecom_pass
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: raj_ecom_db
      MYSQL_USER: raj_ecom_user
      MYSQL_PASSWORD: raj_ecom_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql

volumes:
  mysql_data:
